//Aluna: Gabriela Sena da Silva     2ºTI

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cadastrocelebridades;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela
 */
public class JFTabelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JFTabelaCadastro
     */
    public JFTabelaCadastro() {
        initComponents();
        //MUDAR TABELA AUTOMATICA
        jTCelebridades.setModel(tabelaCelebridade); //o que faz a minha tabela rodar e fazer mudanças que eu faço nela mesma
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAdicionar = new javax.swing.JButton();
        jBRemover = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBRecuperar = new javax.swing.JButton();
        jBLimparTela = new javax.swing.JButton();
        jBGravarArquivo = new javax.swing.JButton();
        jBLerArquivo = new javax.swing.JButton();
        jBCaminhoDoArquivo = new javax.swing.JButton();
        jTFCaminhoDoArquivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFIdade = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFNumSeguidores = new javax.swing.JTextField();
        jTFConta = new javax.swing.JTextField();
        jCBRedeSocial = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCelebridades = new javax.swing.JTable();
        jTFAreaDeAtuacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBRemover.setText("Remover");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBRecuperar.setText("Recuperar");
        jBRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecuperarActionPerformed(evt);
            }
        });

        jBLimparTela.setText("Limpar Tela");
        jBLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparTelaActionPerformed(evt);
            }
        });

        jBGravarArquivo.setText("Gravar Arquivo");
        jBGravarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarArquivoActionPerformed(evt);
            }
        });

        jBLerArquivo.setText("Ler Arquivo");
        jBLerArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLerArquivoActionPerformed(evt);
            }
        });

        jBCaminhoDoArquivo.setText("Caminho do Arquivo");
        jBCaminhoDoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCaminhoDoArquivoActionPerformed(evt);
            }
        });

        jTFCaminhoDoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCaminhoDoArquivoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jTFIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIdadeActionPerformed(evt);
            }
        });

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Idade");

        jLabel4.setText("Conta");

        jLabel5.setText("Rede Social");

        jLabel6.setText("Num Seguidores");

        jTFNumSeguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumSeguidoresActionPerformed(evt);
            }
        });

        jTFConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFContaActionPerformed(evt);
            }
        });

        jCBRedeSocial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Instagram", "Facebook", "Twitter", "Discord" }));
        jCBRedeSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRedeSocialActionPerformed(evt);
            }
        });

        jTCelebridades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Conta", "Idade", "Área de atuação", "Seguidores", "Rede Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTCelebridades);

        jTFAreaDeAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAreaDeAtuacaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Area de Atuação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBGravarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(440, 440, 440))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBLerArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBCaminhoDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCaminhoDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jTFConta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTFAreaDeAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel4)
                                                .addGap(96, 96, 96)
                                                .addComponent(jLabel3)
                                                .addGap(74, 74, 74)
                                                .addComponent(jLabel7)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jTFNumSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel6))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCBRedeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBLimparTela, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionar)
                    .addComponent(jBRemover)
                    .addComponent(jBRecuperar)
                    .addComponent(jBLimparTela)
                    .addComponent(jBAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBRedeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFAreaDeAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCaminhoDoArquivo)
                    .addComponent(jTFCaminhoDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGravarArquivo)
                    .addComponent(jBLerArquivo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        // TODO add your handling code here:
        
        String nome = jTFNome.getText();
        String conta = jTFConta.getText();
        int idade= Integer.parseInt(jTFIdade.getText());
        int numSeguidores = Integer.parseInt(jTFNumSeguidores.getText());
        String redeSocial = jCBRedeSocial.getSelectedItem().toString();
        String areaDeAtuacao = jTFAreaDeAtuacao.getText();
        
        Celebridade celebridades = new Celebridade(nome,conta, idade, areaDeAtuacao, numSeguidores, redeSocial);
        
        tabelaCelebridade.adicionarCelebridade(celebridades);
        
        limparCampos();
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed
        // TODO add your handling code here:
        int linha = jTCelebridades.getSelectedRow();
        
        tabelaCelebridade.removerCelebridade(linha);
    }//GEN-LAST:event_jBRemoverActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        // TODO add your handling code here:
        if(jTCelebridades.getSelectedRow() != -1){
            String nome = jTFNome.getText();
            String conta = jTFNome.getText();
            int idade = Integer.parseInt(jTFIdade.getText());
            int numSeguidores = Integer.parseInt(jTFNumSeguidores.getText());
            String redeSocial = jCBRedeSocial.getSelectedItem().toString();
            String areaDeAtuacao = jTFAreaDeAtuacao.getText();
            
            Celebridade celebridade = new Celebridade(nome, conta, idade, areaDeAtuacao, numSeguidores, redeSocial);
            
            tabelaCelebridade.alterarCelebridade(celebridade, jTCelebridades.getSelectedRow());
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma celebridade!");
        }
        limparCampos();
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecuperarActionPerformed
        // TODO add your handling code here:
        if(jTCelebridades.getSelectedRow() != -1){
            jTFNome.setText(jTCelebridades.getValueAt(jTCelebridades.getSelectedRow(), 0).toString());
            jTFConta.setText(jTCelebridades.getValueAt(jTCelebridades.getSelectedRow(), 1).toString());
            jTFIdade.setText(jTCelebridades.getValueAt(jTCelebridades.getSelectedRow(), 2).toString());
            jTFAreaDeAtuacao.setText(jTCelebridades.getValueAt(jTCelebridades.getSelectedRow(), 3).toString());
            jTFNumSeguidores.setText(jTCelebridades.getValueAt(jTCelebridades.getSelectedRow(), 4).toString());
            jCBRedeSocial.setSelectedItem(jTCelebridades.getValueAt(jTCelebridades.getSelectedRow(), 5));
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma celebridade!");
        }
    }//GEN-LAST:event_jBRecuperarActionPerformed

    private void jBLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparTelaActionPerformed
        // TODO add your handling code here:
        tabelaCelebridade.limparTabela();
    }//GEN-LAST:event_jBLimparTelaActionPerformed

    private void jBGravarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarArquivoActionPerformed
        // TODO add your handling code here
        
        if(caminho.length()>0){
            try{
                arquivo = new File(caminho);
                arquivo.createNewFile();
                JOptionPane.showMessageDialog(null, "Arquivo salvo com sucesso!");
            }
            catch(IOException e){
                System.err.println(e);
            }
            
            FileWriter escrita = null;
            try{
                escrita = new FileWriter(arquivo);
            } catch (IOException ex) {
                Logger.getLogger(JFTabelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            PrintWriter escritaFormatada = new PrintWriter(escrita);
            
            for(int linha = 0; linha < tabelaCelebridade.getRowCount(); linha++ ){
                Celebridade celebridade = tabelaCelebridade.getCelebridade(linha); //
                
                String nome = celebridade.getNome();
                String conta = celebridade.getConta();
                int idade= celebridade.getIdade();
                int numSeguidores = celebridade.getNumSeguidores();
                String redeSocial = celebridade.getRedeSocial();
                String areaDeAtuacao = celebridade.getAreaDeAtuacao();
                
                escritaFormatada.printf("%s;%s;%d;%s;%d;%s;%n", nome, conta, idade, areaDeAtuacao, numSeguidores, redeSocial);
            }
            
            try {
                escrita.close();
            } catch (IOException ex) {
                Logger.getLogger(JFTabelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBGravarArquivoActionPerformed

    private void jBLerArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLerArquivoActionPerformed
        // TODO add your handling code here:
        Scanner leitura = null;
        
        if(caminho.length() > 0){
            try {
                leitura = new Scanner(Paths.get(caminho));
                JOptionPane.showMessageDialog(null, "Arquivo lido com sucesso!");
            } catch (IOException ex) {
                Logger.getLogger(JFTabelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            while(leitura.hasNextLine()){
                
                String linha = leitura.nextLine();
                
                String[] palavras = linha.split(";"); //delimita as plavras em cada posicao pelo ;
                
                String nome = palavras[0];
                String conta = palavras[1];
                int idade= Integer.parseInt(palavras[2]);
                String areaDeAtuacao = palavras[3];
                int numSeguidores = Integer.parseInt(palavras[4]);
                String redeSocial = palavras[5];
        
                Celebridade celebridade = new Celebridade(nome,conta, idade, areaDeAtuacao, numSeguidores, redeSocial);
        
                tabelaCelebridade.adicionarCelebridade(celebridade);
            }
        }
        jTFAreaDeAtuacao.setText("");
    }//GEN-LAST:event_jBLerArquivoActionPerformed

    private void jBCaminhoDoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCaminhoDoArquivoActionPerformed
        // TODO add your handling code here:
        JFileChooser selecaoArquivo = new JFileChooser();
        selecaoArquivo.showOpenDialog(this);
        System.out.println(selecaoArquivo.getSelectedFile().getPath());
        caminho = selecaoArquivo.getSelectedFile().getPath();
        jTFCaminhoDoArquivo.setText(caminho);
    }//GEN-LAST:event_jBCaminhoDoArquivoActionPerformed

    private void jCBRedeSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRedeSocialActionPerformed
        // TODO add your handling code here:
        String verifica;
        verifica =  String.valueOf(jCBRedeSocial.getSelectedItem());
    }//GEN-LAST:event_jCBRedeSocialActionPerformed

    private void jTFAreaDeAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAreaDeAtuacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAreaDeAtuacaoActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jTFContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFContaActionPerformed

    private void jTFIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdadeActionPerformed

    private void jTFNumSeguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumSeguidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumSeguidoresActionPerformed

    private void jTFCaminhoDoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCaminhoDoArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCaminhoDoArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTabelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTabelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTabelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTabelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTabelaCadastro().setVisible(true);
            }
        });
    }
    
    private void limparCampos(){
        jTFNome.setText("");
        jTFConta.setText("");
        jTFIdade.setText("");
        jTFAreaDeAtuacao.setText("");
        jTFNumSeguidores.setText("");
        jTFNome.requestFocus();
    }
    
    private String caminho = "";
    private File arquivo = null;
    private CelebridadeTableModel tabelaCelebridade = new CelebridadeTableModel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCaminhoDoArquivo;
    private javax.swing.JButton jBGravarArquivo;
    private javax.swing.JButton jBLerArquivo;
    private javax.swing.JButton jBLimparTela;
    private javax.swing.JButton jBRecuperar;
    private javax.swing.JButton jBRemover;
    private javax.swing.JComboBox<String> jCBRedeSocial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTCelebridades;
    private javax.swing.JTextField jTFAreaDeAtuacao;
    private javax.swing.JTextField jTFCaminhoDoArquivo;
    private javax.swing.JTextField jTFConta;
    private javax.swing.JTextField jTFIdade;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNumSeguidores;
    // End of variables declaration//GEN-END:variables
}
